name: Build & Publish

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
      - name: 'Login Azure Service Principal'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install Dependencies
        working-directory: repo/Website
        run: npm install
      - name: Build Site
        working-directory: repo/Website
        run: npm run build
      - name: Build API
        working-directory: repo/API
        run: dotnet build --configuration Release --output ./output
      - name: Deploy Infrastructure
        working-directory: repo/Infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: csgotunes
          template: ./csgotunes.json
          parameters: 'spotifyClientSecret=${{ secrets.SPOTIFY_CLIENT_SECRET }}'
      - name: 'Deploy API'
        uses: Azure/functions-action@v1
        working-directory: repo/API
        with:
          app-name: csgotunes
          package: './output'
      - name: Checkout GH Pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          token: '${{ secrets.SERVICE_PAT }}'
          path: 'gh-pages'
      - name: Remove Existing Docs Directory
        working-directory: gh-pages
        run: rm -rf docs
      - name: Create Docs Directory
        working-directory: gh-pages
        run: mkdir -p docs
      - name: Create CNAME File
        working-directory: gh-pages
        run: echo 'www.cstunes.com' > docs/CNAME
      - name: Copy Distribution Folder to Docs
        run: cp -R repo/Website/Distribution/* gh-pages/docs/
      - name: Create Version Text File
        working-directory: gh-pages
        run: echo "$GITHUB_SHA" > docs/version.txt
      - name: Stage Pages
        working-directory: gh-pages/docs
        run: git add -A
      - name: Commit Pages
        working-directory: gh-pages
        run: |
          git config --global user.email "csgotunesservice@gmail.com"
          git config --global user.name "CS:GO Tunes Service Account"
          git commit -m "Pages for $GITHUB_SHA"
      - name: Push Pages
        working-directory: gh-pages
        run: git push origin gh-pages