name: PR Validation

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        working-directory: repo/Website
        run: npm install
      - name: Lint Source
        working-directory: repo/Website
        run: npm run lint
      - name: Build Site
        working-directory: repo/Website
        run: npm run build